### ISSUE TITLE
container LXC

### ISSUE THREAD

**Issue by maximeconnolly** [ClubCedille/docker-debian#1]
Pourquoi ceci n'est pas un container LXC tandis que le reste de l'infrastructure est en LXC.

**Comment by mikefaille** [comment]
LXC et docker ne sont pas fait pour le même use case.
https://insights.ubuntu.com/2016/04/13/stephane-graber-lxd-2-0-docker-in-lxd-712/

**Comment by maximeconnolly** [comment]
Problem est aussi avec la sécurité et aussi le call de libvirt. Tes rendues avec trois kernel de profondeur. Aussi dans ton article directement en bas sa dis que tu peux escaper le docker et le lxc pour devenir root. Si tu active le mode security privelege true. Ton root uid devient le même que ton host. Je pense que même pour un test ceci ne serai pas convenable surtout si la machine ce trouve dans la DMZ de l'école.

**Comment by mikefaille** [comment]
> Problem est aussi avec la sécurité et aussi le call de libvirt. Tes rendues avec trois kernel de profondeur. Aussi dans ton article directement en bas sa dis que tu peux escaper le docker et le lxc pour devenir root. Si tu active le mode security privelege true. Ton root uid devient le même que ton host. Je pense que même pour un test ceci ne serai pas convenable surtout si la machine ce trouve dans la DMZ de l'école.

Én fait, ça c'est pour le cas de LXD. Je n'active pas le mode privilégié de LXC et ça fonctionne super bien.

**Comment by mikefaille** [comment]
Aussi, idéalement, il devrait y avoir 2 niveaux de sécurité puisque l'on est sur la DMZ de l'école. Or, il n'est pas prudent de mettre une BD comme LDAP sur la DMZ. Puisqu'un container n'est pas sécuritaire au niveau de la mémoire partagé, je crois que l'on se rejoint là-dessus.

**Comment by mikefaille** [comment]
Je close le ticket parce que la sécurité de docker est contenu dans LXC en mode non privilégié.

**Comment by mikefaille** [comment]
Cette image Docker dont les autres peuvent être utilisés dans d'autres conditions que celle présenté sur la DMZ. Pour le design de la DMZ et la sécurité, je propose d'apporter ton point à la prochaine réunion sysadmin. Je suis d'accord avec toi.

**Comment by mikefaille** [comment]
@maximest-pierre ça va t'intéresser : https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2016/april/understanding-and-hardening-linux-containers/
